### ISSUE TITLE
`brew cask install alfred-numi` results in a 404

### ISSUE THREAD

**Issue by BenLeggiero** [nikolaeu/Numi#133]
I was excited to see that Numi had Alfred integration, so I installed Numi in hopes I could do cool complex calculations in Alfred. I opened the preferences and saw that the Alfred integration was not as plug-and-play as I'd hoped, instead involving using `brew` to install it. No worries, though; I'm a software engineer and more than capable of doing that.

Then, after some weirdness with it failing if Alfred is already installed, I got to this step and couldn't get past it:

```
benleggiero % brew cask install alfred-numi

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

2019-10-23 18:17:28.448 defaults[28736:509693] 
The domain/default pair of (/Users/benleggiero/Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist, syncfolder) does not exist
==> Satisfying dependencies
All Cask dependencies satisfied.
==> Downloading https://github.com/nikolaeu/Numi-extensions/releases/download/1.3/Numi.alfredworkflo
==> Downloading from https://github.com/nikolaeu/Numi/releases/download/1.3/Numi.alfredworkflow

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'alfred-numi' with message: Download failed: https://github.com/nikolaeu/Numi-extensions/releases/download/1.3/Numi.alfredworkflow
```

It seems Numi is missing something it promised Homebrew that it would host, so I can't use this advertised feature of Numi+Alfred integration.

**Comment by nikolaeu** [comment]
Have you tried direct extension download ? https://github.com/nikolaeu/Numi/releases/download/mac-3.20.4/Numi.alfredworkflow

**Comment by BenLeggiero** [comment]
@nikolaeu The bug I was reporting only dealt with [the other set of instructions you had up](https://github.com/nikolaeu/Numi/wiki/Documentation/_compare/ed80e525219a1c9e20c9614500a254ccceefb407...fd39c8c80bd164c3c499f2d46a29fe01a0caff9d).
