### ISSUE TITLE
Notification Center widget

### ISSUE THREAD

**Issue by pyinto** [nikolaeu/numi#163]
Numi widget is available in the Notification Center but it looks like it does not work, it always shows just blank widget, any input in the main app window doesn't change anything. 

I just installed numi app from scratch. MacOS 10.15.4
<img width="342" alt="image" src="https://user-images.githubusercontent.com/19248049/81498151-d23bd200-92f5-11ea-8fd7-7dac7a06b67b.png">

**Comment by satanworker** [comment]
I have kind of similar issue. 
Notification widget was working absolutely fine, but at some point in hangs entirely and 
<img width="354" alt="CleanShot 2020-05-11 at 11 56 36@2x" src="https://user-images.githubusercontent.com/11026240/81537574-7a957900-937e-11ea-9e54-8c364dc8f7b4.png"> and always display the same data, I can't change it or do anything. 
- restart didn't help
- complete numi uninstall didn't help
- kiling notification centre in activity monitor didn't help
Thank you for this application, it's great! hope you'll be able to solve the bug

**Comment by altokarev** [comment]
I've got the same issue as @pyinto.

@nikolaeu is there any workaround or a fix?

Thanks!

**Comment by nikolaeu** [comment]
Seems like a bug, fix should follow soon

**Comment by nikolaeu** [comment]
New build with widget fix: https://s5.numi.app/updates/3.27.664/Numi.zip
@pyinto @altokarev @satanworker

**Comment by pyinto** [comment]
@nikolaeu it works for me, thank you!

**Comment by altokarev** [comment]
@nikolaeu thank you!

Yep, now it works, but the `Open Numi` button issue is still here.
