### ISSUE TITLE
XCode 8.1

### ISSUE THREAD

**Issue by dashie** [nikolaeu/Numi#29]
Using XCode 8.1 I have this error `/Users/username/Downloads/NumiKit-0.12/SampleNumiPlugin.swift:10:8: Module file was created by an older version of the compiler; rebuild 'Numi' and try again: /Users/username/Downloads/NumiKit-0.12/Numi.framework/Modules/Numi.swiftmodule/x86_64.swiftmodule` and I connot compile the project.

**Comment by nikolaeu** [comment]
Yeah, downsides of swift plugins is that all should be compiled with the same version of compiler. Working on new plugin system atm. Will post update as soon as it will be ready to test/develop!

**Comment by nferro** [comment]
Isn't there any workaround for this?

**Comment by nikolaeu** [comment]
@nferro sadly, no. Keep pushing JS plugins ATM.

**Comment by TarekSalama** [comment]
Is the project open source? Can I look into its Swift files?

**Comment by nikolaeu** [comment]
Not open-sourced yet :(

**Comment by hbakhtiyor** [comment]
@nikolaeu any open source alternatives? :)

**Comment by nikolaeu** [comment]
@hbakhtiyor ¯\_(ツ)_/¯
