### ISSUE TITLE
Missing syntax highlighting

### ISSUE THREAD

**Issue by matt3224** [nikolaeu/Numi#37]
Running Version 3.15.2 (122)

![screen shot 2017-06-19 at 10 52 35 am](https://user-images.githubusercontent.com/2401925/27279729-7715379e-54dd-11e7-91f3-cadf0f4bf397.png)

**Comment by nikolaeu** [comment]
@matt3224 text content will be really helpful!

**Comment by matt3224** [comment]
[test quote.numi.zip](https://github.com/nikolaeu/Numi/files/1101844/test.quote.numi.zip)

Heres the export

**Comment by nikolaeu** [comment]
@matt3224 Issue should be fixed now in development version! Here is download link for it: http://numi.io/static/dev/Numi.zip
Will appreciate for feedback!

**Comment by matt3224** [comment]
Fantastic, it works. Good Job!
